### ISSUE TITLE
Strange russian code generation

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#96] opened 2018-10-22 17:10 UTC
Sometimes Jhelper generating such code. 
```std::ifstream in("стандартный ввод");```
```std::ofstream out("стандартный вывод");```
```solver.solve(in, out);```

**Comment by emli** [comment] 2018-10-22 17:15
https://github.com/emli/competitive/blob/master/output/main.cpp

**Comment by emli** [comment] 2018-10-22 17:20
Discovered bug. It happens only when I was switched to Russian version of codeforces

**Comment by AlexeyDmitriev** [comment] 2018-10-24 19:31
I got this today too, I'll investigate

**Comment by AlexeyDmitriev** [comment] 2018-10-28 21:16
So, as far as I understand, the issue is in Competitive companion plugin. I raised an there(jmerle/competitive-companion#14). Meanwhile, you can use Chelper plugin or english version of CF

**Comment by jmerle** [comment] 2018-10-28 23:16
I merged the Alexey's patch and published Competitive Companion 2.4.1 to the Chrome Web Store and Mozilla's AMO. Depending on your browser it can take up to 24 hours until it automatically updates the extension.

**Closed** 2018-10-29 09:56 UTC
